drop table Client;

CREATE TABLE Client
(
    Id_client NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Name_Client NVARCHAR2(20) NOT NULL,
    Surname_Client NVARCHAR2(20) NOT NULL,
    Login_Client NVARCHAR2(20) NOT NULL,
    Password_Client NVARCHAR2(20) NOT NULL,
    Photo_Client BLOB,
    Mail_Client NVARCHAR2(30) NOT NULL
);

ALTER TABLE Client
MODIFY (Password_Client NVARCHAR2(250));
ALTER TABLE Client
ADD CONSTRAINT UQ_Login_Client UNIQUE (Login_Client);


CREATE TABLE Specialization
(
    Spezialization_Name NVARCHAR2(60) PRIMARY KEY
);

CREATE TABLE Academic_Degree
(
    Academic_Name NVARCHAR2(60) PRIMARY KEY
);
drop table Psychologist;
CREATE TABLE Psychologist (
    Id_Psychologist NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Name_Psychologist NVARCHAR2(20) NOT NULL,
    Surname_Psychologist NVARCHAR2(20) NOT NULL,
    Patronymic_Psychologist NVARCHAR2(20) NOT NULL,
    Experience NUMBER NOT NULL CHECK (Experience >= 0 AND Experience <= 50),
    Photo_Psychologist BLOB,
    Description NVARCHAR2(300),
    Spezialization_Psychologist NVARCHAR2(60) NOT NULL,
    Degree NVARCHAR2(60) NOT NULL,
    CONSTRAINT FK_Specialization
        FOREIGN KEY (Spezialization_Psychologist) 
        REFERENCES Specialization(Spezialization_Name)
        ON DELETE CASCADE,
    CONSTRAINT FK_Academic_Degree
        FOREIGN KEY (Degree) 
        REFERENCES Academic_Degree(Academic_Name)
        ON DELETE CASCADE
);
drop table Voucher;
CREATE TABLE Voucher (
    Id_Voucher NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Date_Voucher DATE NOT NULL,
    Time_Voucher_Start TIMESTAMP NOT NULL,
    Time_Voucher_End TIMESTAMP NOT NULL,
    Id_Psychologist NUMBER NOT NULL,
    Ordered CHAR(10) NOT NULL,
    CONSTRAINT FK_Psychologist
        FOREIGN KEY (Id_Psychologist)
        REFERENCES Psychologist(Id_Psychologist)
        ON DELETE CASCADE
);
----------------------------drop table Procedures;
CREATE TABLE Procedures (
    Id_Procedure NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Name_Procedure NVARCHAR2(30) NOT NULL,
    Price FLOAT NOT NULL CHECK (Price > 0 AND Price <= 10000),
    Depiction NVARCHAR2(150) NOT NULL,
    Spezialization_Procedure NVARCHAR2(60),
    Photo_Procedure BLOB,
    CONSTRAINT FK_Spezialization_Procedure
        FOREIGN KEY (Spezialization_Procedure)
        REFERENCES Specialization(Spezialization_Name)
        ON DELETE CASCADE
);
drop table Timetable;
CREATE TABLE Timetable (
    Id_Psychologist NUMBER PRIMARY KEY,
    MondStart TIMESTAMP,
    MondEnd TIMESTAMP,
    TueStart TIMESTAMP,
    TueEnd TIMESTAMP,
    WenStart TIMESTAMP,
    WenEnd TIMESTAMP,
    ThuStart TIMESTAMP,
    ThuEnd TIMESTAMP,
    FriStart TIMESTAMP,
    FriEnd TIMESTAMP,
    CONSTRAINT FK_Timetable_Psychologist
        FOREIGN KEY (Id_Psychologist)
        REFERENCES Psychologist(Id_Psychologist)
        ON DELETE CASCADE
);
drop table Booking;
CREATE TABLE Booking (
    ID_Booking NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Date_Booking DATE NOT NULL,
    Id_Procedure NUMBER NOT NULL,
    Id_Client NUMBER NOT NULL,
    Id_Psychologist NUMBER NOT NULL,
    Id_Voucher NUMBER NOT NULL,
    Time_Booking TIMESTAMP,
    CONSTRAINT FK_Booking_Procedure
        FOREIGN KEY (Id_Procedure)
        REFERENCES Procedures(Id_Procedure)
        ON DELETE CASCADE,
    CONSTRAINT FK_Booking_Client
        FOREIGN KEY (Id_Client)
        REFERENCES Client(Id_Client)
        ON DELETE CASCADE,
    CONSTRAINT FK_Booking_Psychologist
        FOREIGN KEY (Id_Psychologist)
        REFERENCES Psychologist(Id_Psychologist)
        ON DELETE CASCADE,
    CONSTRAINT FK_Booking_Voucher
        FOREIGN KEY (Id_Voucher)
        REFERENCES Voucher(Id_Voucher)
        ON DELETE CASCADE
);
drop table Review;
CREATE TABLE Review (
    Id_Review NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Photo_Review BLOB,
    Name_Client NVARCHAR2(20) NOT NULL,
    Id_Client NUMBER NOT NULL,
    Review NVARCHAR2(140) NOT NULL,
    CONSTRAINT FK_Review_Client
        FOREIGN KEY (Id_Client)
        REFERENCES Client(Id_Client)
        ON DELETE CASCADE
);

drop table CustomerInteraction;

CREATE TABLE CustomerInteraction (
    Id_Psychologist NUMBER NOT NULL,
    Id_Client NUMBER NOT NULL,
    Interaction_Timestamp TIMESTAMP(9) NOT NULL,
    Success VARCHAR2(10) CHECK (Success IN ('дю', 'мер')) NOT NULL,
    CONSTRAINT PK_CustomerInteraction PRIMARY KEY (Interaction_Timestamp),
    CONSTRAINT FK_CustomerInteraction_Psychologist
        FOREIGN KEY (Id_Psychologist)
        REFERENCES Psychologist(Id_Psychologist)
        ON DELETE CASCADE,
    CONSTRAINT FK_CustomerInteraction_Client
        FOREIGN KEY (Id_Client)
        REFERENCES Client(Id_Client)
        ON DELETE CASCADE
);