//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanBrain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public short ID_Booking { get; set; }
        public System.DateTime Date_Booking { get; set; }
        public int Id_Procedure { get; set; }
        public int Id_Client { get; set; }
        public int Id_Psychologist { get; set; }
        public int Id_Voucher { get; set; }
        public Nullable<System.TimeSpan> Time_Booking { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Procedure Procedure { get; set; }
        public virtual Psychologist Psychologist { get; set; }
        public virtual Voucher Voucher { get; set; }
    }
}
