//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanBrain
{
    using CleanBrain.ManagerFrame;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    public partial class Client : INotifyPropertyChanged
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Bookings = new HashSet<Booking>();
            this.Reviews = new HashSet<Review>();
            this.Login_Client = ManagerItem.isRussian ? "логин" : "login";
            this.Mail_Client = ManagerItem.isRussian ? "электронная почта" : "email";
            this.Password_Client = ManagerItem.isRussian ? "пароль" : "password";
            this.Name_Client = "Name";
            this.Surname_Client = "Surname";

        }

        private string name;
        private string surname;
        private string login;
        private string password;
        private string email;
        public int Id_client { get; set; }
        public string Name_Client
        {
            get { return name; }
            set
            {
                name = value;
                OnPropertyChanged("Name_Client");
            }
        }
        public string Surname_Client
        {
            get { return surname; }
            set
            {
                surname = value;
                OnPropertyChanged("Surname_Client");
            }
        }
        public string Login_Client
        {
            get { return login; }
            set
            {
                login = value;
                OnPropertyChanged("Login_Client");
            }
        }
        public string Password_Client
        {
            get { return password; }
            set
            {
                password = value;
                OnPropertyChanged("Password_Client");
            }
        }
        public byte[] Photo_Client { get; set; }
        public string Mail_Client
        {
            get { return email; }
            set
            {
                email = value;
                OnPropertyChanged("Mail_Client");
            }
        }
        public event PropertyChangedEventHandler PropertyChanged;
        public void OnPropertyChanged([CallerMemberName] string prop = "")
        {
            if (PropertyChanged != null)
                PropertyChanged(this, new PropertyChangedEventArgs(prop));
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
