//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanBrain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    public partial class Psychologist : INotifyPropertyChanged
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Psychologist()
        {
            this.Bookings = new HashSet<Booking>();
            this.Vouchers = new HashSet<Voucher>();
        }
        private int _id;
        private string _name;
        private string _description;
        private string _surname;
        private string _patronymic;
        private short _exp;
        private string _spec;
        private string _degree;


        public int Id_Psychologist
        {
            get { return _id; }
            set
            {
                _id = value;
                OnPropertyChanged("Id_Psychologist");
            }
        }
        public string Name_Psychologist
        {
            get { return _name; }
            set
            {
                _name = value;
                OnPropertyChanged("Name_Psychologist");
            }
        }
        public string Surname_Psychologist
        {
            get { return _surname; }
            set
            {
                _surname = value;
                OnPropertyChanged("Surname_Psychologist");
            }
        }
        public string Patronymic_Psychologist
        {
            get { return _patronymic; }
            set
            {
                _patronymic = value;
                OnPropertyChanged("Patronymic_Psychologist");
            }
        }
        public short Experience
        {
            get { return _exp; }
            set
            {
                _exp = value;
                OnPropertyChanged("Experience");
            }
        }
        public byte[] Photo_Psychologist { get; set; }
        public string Description
        {
            get { return _description; }
            set
            {
                _description = value;
                OnPropertyChanged("Description");
            }
        }
        public string Spezialization_Psychologist
        {
            get { return _spec; }
            set
            {
                _spec = value;
                OnPropertyChanged("Spezialization_Psychologist");
            }
        }
        public string Degree
        {
            get { return _degree; }
            set
            {
                _degree = value;
                OnPropertyChanged("Degree");
            }
        }

        public event PropertyChangedEventHandler PropertyChanged;
        public void OnPropertyChanged([CallerMemberName] string prop = "")
        {
            if (PropertyChanged != null)
                PropertyChanged(this, new PropertyChangedEventArgs(prop));
        }

        public virtual Academic_Degree Academic_Degree { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual Specialization Specialization { get; set; }
        public virtual Timetable Timetable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Voucher> Vouchers { get; set; }
    }
}
