//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanBrain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    public partial class Timetable : INotifyPropertyChanged
    {
        private int _id;
        private Nullable<System.TimeSpan> mondstart;
        private Nullable<System.TimeSpan> mondend;
        private Nullable<System.TimeSpan> tuestart;
        private Nullable<System.TimeSpan> tueend;
        private Nullable<System.TimeSpan> wenstart;
        private Nullable<System.TimeSpan> wenend;
        private Nullable<System.TimeSpan> thustart;
        private Nullable<System.TimeSpan> thuend;
        private Nullable<System.TimeSpan> fristart;
        private Nullable<System.TimeSpan> friend;
        public int Id_Psychologist
        {
            get { return _id; }
            set
            {
                _id = value;
                OnPropertyChanged("Id_Psychologist");
            }
        }
        public Nullable<System.TimeSpan> MondStart
        {
            get { return mondstart; }
            set
            {
                mondstart = value;
                OnPropertyChanged("MondStart");
            }
        }
        public Nullable<System.TimeSpan> MondEnd
        {
            get { return mondend; }
            set
            {
                mondend = value;
                OnPropertyChanged("MondEnd");
            }
        }
        public Nullable<System.TimeSpan> TueStart
        {
            get { return tuestart; }
            set
            {
                tuestart = value;
                OnPropertyChanged("TueStart");
            }
        }
        public Nullable<System.TimeSpan> TueEnd
        {
            get { return tueend; }
            set
            {
                tueend = value;
                OnPropertyChanged("TueEnd");
            }
        }
        public Nullable<System.TimeSpan> WenStart
        {
            get { return wenstart; }
            set
            {
                wenstart = value;
                OnPropertyChanged("WenStart");
            }
        }
        public Nullable<System.TimeSpan> WenEnd
        {
            get { return wenend; }
            set
            {
                wenend = value;
                OnPropertyChanged("WenEnd");
            }
        }
        public Nullable<System.TimeSpan> ThuStart
        {
            get { return thustart; }
            set
            {
                thustart = value;
                OnPropertyChanged("ThuStart");
            }
        }
        public Nullable<System.TimeSpan> ThuEnd
        {
            get { return thuend; }
            set
            {
                thuend = value;
                OnPropertyChanged("ThuEnd");
            }
        }
        public Nullable<System.TimeSpan> FriStart
        {
            get { return fristart; }
            set
            {
                fristart = value;
                OnPropertyChanged("FriStart");
            }
        }
        public Nullable<System.TimeSpan> FriEnd
        {
            get { return friend; }
            set
            {
                friend = value;
                OnPropertyChanged("FriEnd");
            }
        }

        public event PropertyChangedEventHandler PropertyChanged;
        public void OnPropertyChanged([CallerMemberName] string prop = "")
        {
            if (PropertyChanged != null)
                PropertyChanged(this, new PropertyChangedEventArgs(prop));
        }

        public virtual Psychologist Psychologist { get; set; }
    }
}
