//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanBrain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voucher()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int Id_Voucher { get; set; }
        public System.DateTime Date_Voucher { get; set; }
        public System.TimeSpan Time_Voucher_Start { get; set; }
        public System.TimeSpan Time_Voucher_End { get; set; }
        public int Id_Psychologist { get; set; }
        public string Ordered { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual Psychologist Psychologist { get; set; }
    }
}
